//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HisRoyalRedness.com.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HisRoyalRedness.com.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add a {0} ({1}) to a {2} ({3}).
        /// </summary>
        internal static string CALCENGINE_AddErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_AddErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t AND a {0} ({1}) to a {2} ({3}).
        /// </summary>
        internal static string CALCENGINE_AndErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_AndErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t divide a {2} ({3}) by a {0} ({1}).
        /// </summary>
        internal static string CALCENGINE_DivideErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_DivideErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t left-shift a {0} ({1}) by a {2} ({3}).
        /// </summary>
        internal static string CALCENGINE_LeftShiftErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_LeftShiftErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t divide a {2} ({3}) by a {0} ({1}).
        /// </summary>
        internal static string CALCENGINE_ModuloErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_ModuloErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t multiply a {0} ({1}) with a {2} ({3}).
        /// </summary>
        internal static string CALCENGINE_MultiplyErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_MultiplyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t OR a {0} ({1}) with a {2} ({3}).
        /// </summary>
        internal static string CALCENGINE_OrErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_OrErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t raise a {0} ({1}) to the power of a {2} ({3}).
        /// </summary>
        internal static string CALCENGINE_PowerErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_PowerErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t right-shift a {0} ({1}) by a {2} ({3}).
        /// </summary>
        internal static string CALCENGINE_RightShiftErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_RightShiftErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t calculate the {2} ({3}) root of {0} ({1}).
        /// </summary>
        internal static string CALCENGINE_RootErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_RootErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t subtract a {2} ({3}) from a {0} ({1}).
        /// </summary>
        internal static string CALCENGINE_SubtractErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_SubtractErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t XOR a {0} ({1}) with a {2} ({3}).
        /// </summary>
        internal static string CALCENGINE_XorErrorMessage {
            get {
                return ResourceManager.GetString("CALCENGINE_XorErrorMessage", resourceCulture);
            }
        }
    }
}
